version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: alumni-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: alumni-platform
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - alumni-network

  # Alumni Platform Application
  app:
    build: .
    container_name: alumni-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/alumni-platform?authSource=admin
      SESSION_SECRET: your-production-session-secret-here
      CLOUDINARY_URL: cloudinary://api_key:api_secret@cloud_name
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - alumni-network
    volumes:
      - ./uploads:/app/uploads

volumes:
  mongodb_data:
    driver: local

networks:
  alumni-network:
    driver: bridge